server:
  port: 8082

spring:
  application:
    name: article-service
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: localhost:8848
  flyway:
    out-of-order: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: # 数据库密码
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    com.example.blog.article: DEBUG
    org.hibernate.SQL: DEBUG